language: node_js
sudo: false
node_js:
- 0.10.33
branches:
  only:
  - master
  - sauce-labs
env:
  global:
    - secure: FbBoPOFduql+4/2r8fJ/V9jdMMVsGEEyoJq73rAE5DSSTU7oaquu9NnKUGTkBRaaI9VW0PmeUzYhW+2esVbwkGeujozeztJRf0l6BCfKA0n1TGgBQRSMt48RrpVd9QJP5OR3Gjm/qgDD8OClAF3GorMLhoobq2HaIhuAjuOst8uflyUD1Bi5BE+wZI+pKht5/9mRTx/oXreb1Ns+LUUJCgYFUY2GHe/WCa5swrAVA6LBenj+V7pCXu8oigca31ff0kQTPXg+StDMFNvGP/KcLk1vA8EqMrG1xquXbb0tgLuF2SD/I8v0hWwJwB1LOVCQrPvWFwqOeZUdQdNW4esBztT80zGhvL9PKqH1tAN+G1bY7yryHnewYdK73OtQdERuwM4GT6DE9hULF8JZARMO41Sj0VqjBAoVSITtdpO6j7bneNfbPOPeS9X1XLjMQPnqL/w9xr3h+zUevnzDfgkdep3FwkOIgWIkdxRrMSOBmavYE9+ZG59w+5kRLDN2nW003xv9tpNjafsu9Zw1LXYR7rzCYMGYlYR7qP7+bA/gNBXEq6dFR3LwEKQ/aOMS0NJZ9+nqM4k7jDrnoclDK1r+K+daFdwwBTiyV3s70/WhNPcaZeryuj2oT5gPBk4ZmVNqKlqdVyljCtqXaoXfH23EiPNdgWDAamD5IuRhTMftD2g=
    - secure: mNbRoqmgTsztVEJzQvtsSxlu+UAiLeYltjUI6wPcbbaHXSImfWfT9JZG7yKdIoiaviiFhADSEiNe49WBq+up9ZkR2Qr5Cynb6mQOXj2+TGl2FLUh6PsjNRVGZBaJYwTB6SXviynYPqspTo07zvtdYv6SpztJ7lbQWa0/UkUqMWRvkln+yHaJNafseWAPbhXBcVrqKhNyEBRIDuLlgNR3B0UxHNk2g3bw+4P7i35+WsAoUSpkOBly5AWLqVlzx/uQbmHR3XnxGZEGrQYQMKu1SLuhhXxTdnSVOBFvfLgsxkfrBdyphnEIRbz/ygOjhSVETYuSfvF3Fx5K+5LvJ1Gzpesq4uAOAatnv+pBD53kRvk1SfIpY/3zl8XkD9AfUEMVhoV1ECZGB5JKmsxpDr6R0xBftIGaJczUNDXc4Y1YN7PBkK8trJIqkAmw3kKk5eSk2LAsKCps6ClnCP7yxjVdgNuaH/zkCww9iB8IIhsBchELLpW/w+r7UG06FnzgHmPYL08F3p25sFbRU3/PkfHV1JKul35lC+B2rWU+aO32qIuLJA8HwfucglCS2Xhr60z8euOVAgdaDi75Q6fSl9Fn8R7mJZdDrP9yKra8eaYbbC17TpPiT+aPxKOnGNbFbbq/HLe87uEDXfEgTGuobMv1Ut3GfTfbGd8A5PMWKaa8VC8=
addons:
  sauce_connect: true
cache:
  directories:
    - node_modules